/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.vertx.starter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        // MainVerticle classUnderTest = new MainVerticle();
        // try {
        //     classUnderTest.start();
        // } catch (Exception e) {
        //     // TODO Auto-generated catch block
        //     e.printStackTrace();
        // }

    }
}
